# Generated by Django 5.2.9 on 2026-01-04 22:05

import attachments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lawsuits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('identity', 'هوية/جواز سفر'), ('contract', 'عقد'), ('certificate', 'شهادة'), ('evidence', 'دليل'), ('statement', 'بيان'), ('receipt', 'إيصال'), ('other', 'أخرى')], default='other', max_length=50, verbose_name='نوع المستند')),
                ('gregorian_date', models.DateField(verbose_name='التاريخ الميلادي')),
                ('hijri_date', models.CharField(max_length=50, verbose_name='التاريخ الهجري')),
                ('page_count', models.PositiveIntegerField(default=1, verbose_name='عدد الصفحات')),
                ('content', models.TextField(verbose_name='مضمون المستند')),
                ('evidence_basis', models.TextField(verbose_name='وجه الاستدلال')),
                ('file', models.FileField(upload_to=attachments.models.attachment_upload_path, verbose_name='الملف المرفق')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='اسم الملف الأصلي')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم الملف (بايت)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('lawsuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='lawsuits.lawsuit', verbose_name='الدعوى')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'مرفقات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lawsuit'], name='attachments_lawsuit_34dc7e_idx'), models.Index(fields=['document_type'], name='attachments_documen_5a76b4_idx'), models.Index(fields=['gregorian_date'], name='attachments_gregori_f30149_idx')],
            },
        ),
    ]
