CREATE TABLE "accounts_userprofile" ("id" integer NOT NULL PRIMARY KEY , "role" varchar(20) NOT NULL, "phone_number" varchar(20) NULL, "national_id" varchar(20) NULL UNIQUE, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, "is_active" bool NOT NULL, "user_id" integer NOT NULL UNIQUE REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "appeals_appeal" ("id" integer NOT NULL PRIMARY KEY , "appeal_type" varchar(50) NOT NULL, "appeal_number" varchar(100) NOT NULL UNIQUE, "appeal_reasons" text NOT NULL, "appeal_requests" text NOT NULL, "higher_court" varchar(200) NOT NULL, "status" varchar(50) NOT NULL, "appeal_date" date NOT NULL, "hijri_date" varchar(50) NULL, "submitted_by" varchar(200) NOT NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, "lawsuit_id" bigint NOT NULL REFERENCES "lawsuits_lawsuit" ("id") DEFERRABLE INITIALLY DEFERRED, "submitted_by_user_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "attachments_attachment" ("id" integer NOT NULL PRIMARY KEY , "document_type" varchar(50) NOT NULL, "gregorian_date" date NOT NULL, "hijri_date" varchar(50) NOT NULL, "page_count" integer NOT NULL CHECK ("page_count" >= 0), "content" text NOT NULL, "evidence_basis" text NOT NULL, "file" varchar(100) NOT NULL, "original_filename" varchar(255) NOT NULL, "file_size" integer NULL CHECK ("file_size" >= 0), "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, "lawsuit_id" bigint NOT NULL REFERENCES "lawsuits_lawsuit" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "audit_auditlog" ("id" integer NOT NULL PRIMARY KEY , "action_type" varchar(50) NOT NULL, "description" text NOT NULL, "metadata" text NOT NULL ), "ip_address" char(39) NULL, "timestamp" timestamp NOT NULL, "lawsuit_id" bigint NULL REFERENCES "lawsuits_lawsuit" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY , "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY , "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY , "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE TABLE "auth_user" ("id" integer NOT NULL PRIMARY KEY , "password" varchar(128) NOT NULL, "last_login" timestamp NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" timestamp NOT NULL, "first_name" varchar(150) NOT NULL);
CREATE TABLE "auth_user_groups" ("id" integer NOT NULL PRIMARY KEY , "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "auth_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY , "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "book_nodes" ("id" bigint NOT NULL PRIMARY KEY, "source_title" varchar(255) NOT NULL, "level" varchar(50) NOT NULL, "title" text NOT NULL, "body" text NULL, "parent_id" bigint NULL, "page_from" integer NULL, "page_to" integer NULL);
CREATE TABLE "courts_court" ("id" integer NOT NULL PRIMARY KEY , "name" varchar(200) NOT NULL, "address" text NULL, "location_url" varchar(500) NULL, "latitude" decimal NULL, "longitude" decimal NULL, "is_active" bool NOT NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, "court_type_id" bigint NULL REFERENCES "courts_courttype" ("id") DEFERRABLE INITIALLY DEFERRED, "district_id" bigint NULL REFERENCES "courts_district" ("id") DEFERRABLE INITIALLY DEFERRED, "governorate_id" bigint NULL REFERENCES "courts_governorate" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "courts_court_specializations" ("id" integer NOT NULL PRIMARY KEY , "court_id" bigint NOT NULL REFERENCES "courts_court" ("id") DEFERRABLE INITIALLY DEFERRED, "courtspecialization_id" bigint NOT NULL REFERENCES "courts_courtspecialization" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "courts_courtspecialization" ("id" integer NOT NULL PRIMARY KEY , "name" varchar(150) NOT NULL UNIQUE, "description" text NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL);
CREATE TABLE "courts_courttype" ("id" integer NOT NULL PRIMARY KEY , "name" varchar(150) NOT NULL, "judicial_level" varchar(50) NOT NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL);
CREATE TABLE "courts_district" ("id" integer NOT NULL PRIMARY KEY , "name" varchar(150) NOT NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, "governorate_id" bigint NOT NULL REFERENCES "courts_governorate" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "courts_governorate" ("id" integer NOT NULL PRIMARY KEY , "name" varchar(150) NOT NULL UNIQUE, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL);
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY , "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" timestamp NOT NULL);
CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY , "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY , "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" timestamp NOT NULL);
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" timestamp NOT NULL);
CREATE TABLE "hearings_hearing" ("id" integer NOT NULL PRIMARY KEY , "hearing_date" date NOT NULL, "hijri_date" varchar(50) NULL, "hearing_time" time NULL, "notes" text NOT NULL, "judge_name" varchar(200) NULL, "hearing_type" varchar(50) NOT NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, "created_by_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "judge_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "lawsuit_id" bigint NOT NULL REFERENCES "lawsuits_lawsuit" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "judgments_judgment" ("id" integer NOT NULL PRIMARY KEY , "judgment_type" varchar(50) NOT NULL, "judgment_number" varchar(100) NOT NULL, "judgment_date" date NOT NULL, "hijri_date" varchar(50) NULL, "judgment_text" text NOT NULL, "summary" text NULL, "judge_name" varchar(200) NOT NULL, "court_name" varchar(200) NOT NULL, "status" varchar(50) NOT NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, "created_by_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "judge_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "lawsuit_id" bigint NOT NULL REFERENCES "lawsuits_lawsuit" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "laws_caselegalreference" ("id" integer NOT NULL PRIMARY KEY , "confidence_score" decimal NULL, "is_ai" bool NOT NULL, "notes" text NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, "lawsuit_id" bigint NOT NULL REFERENCES "lawsuits_lawsuit" ("id") DEFERRABLE INITIALLY DEFERRED, "article_id" bigint NOT NULL REFERENCES "laws_lawarticle" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "laws_law" ("id" integer NOT NULL PRIMARY KEY , "name" varchar(300) NOT NULL, "issue_year" integer NULL, "description" text NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, "category_id" bigint NULL REFERENCES "laws_legalcategory" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "laws_lawarticle" ("id" integer NOT NULL PRIMARY KEY , "article_number" varchar(50) NOT NULL, "article_text" text NOT NULL, "order" integer NOT NULL CHECK ("order" >= 0), "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, "section_id" bigint NOT NULL REFERENCES "laws_lawsection" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "laws_lawchapter" ("id" integer NOT NULL PRIMARY KEY , "title" varchar(300) NOT NULL, "chapter_number" varchar(50) NULL, "order" integer NOT NULL CHECK ("order" >= 0), "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, "law_id" bigint NOT NULL REFERENCES "laws_law" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "laws_lawsection" ("id" integer NOT NULL PRIMARY KEY , "title" varchar(300) NOT NULL, "section_number" varchar(50) NULL, "order" integer NOT NULL CHECK ("order" >= 0), "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, "chapter_id" bigint NOT NULL REFERENCES "laws_lawchapter" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "laws_legalcategory" ("id" integer NOT NULL PRIMARY KEY , "name" varchar(150) NOT NULL UNIQUE, "description" text NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL);
CREATE TABLE "lawsuits_financialclaim" ("id" integer NOT NULL PRIMARY KEY , "amount" decimal NULL, "currency" varchar(3) NOT NULL, "due_date" date NULL, "description" text NULL, "created_at" timestamp NOT NULL, "lawsuit_id" bigint NOT NULL REFERENCES "lawsuits_lawsuit" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "lawsuits_lawsuit" ("id" integer NOT NULL PRIMARY KEY , "case_number" varchar(100) NOT NULL UNIQUE, "gregorian_date" date NULL, "hijri_date" varchar(50) NULL, "court" varchar(200) NULL, "subject" varchar(150) NOT NULL, "facts" text NULL, "reasons" text NULL, "requests" text NULL, "status" varchar(50) NOT NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, "created_by_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "court_fk_id" bigint NULL REFERENCES "courts_court" ("id") DEFERRABLE INITIALLY DEFERRED, "description" text NULL, "filing_date" date NULL, "legal_basis" text NULL, "case_status" varchar(50) NOT NULL, "governorate" varchar(50) NULL, "legal_reasons" text NULL, "notes" text NULL, "case_type" varchar(50) NOT NULL);
حيث إن في ذمة المطلوب الأمر ضده مبلغاً ثابتاً بالكتابة، وحال الأداء، ولم يقم بالسداد حتى تاريخه.',NULL,'ثانياً: الطلبات
نلتمس من عدالتكم إصدار أمر أداء بإلزام المطلوب الأمر ضده بسداد المبلغ محل الطلب مع الرسوم.','pending','2026-01-06 21:44:08.901683','2026-01-06 21:44:08.901683',1,NULL,NULL,'2026-01-07',NULL,'جديد',NULL,NULL,NULL,'امر_اداء');
CREATE TABLE "lawsuits_legaltemplate" ("id" integer NOT NULL PRIMARY KEY , "case_type" varchar(50) NOT NULL, "section_key" varchar(50) NOT NULL, "section_title" varchar(100) NOT NULL, "default_text" text NOT NULL, "is_required" bool NOT NULL);
حيث إن في ذمة المطلوب الأمر ضده مبلغاً ثابتاً بالكتابة، وحال الأداء، ولم يقم بالسداد حتى تاريخه.',1);
نلتمس من عدالتكم إصدار أمر أداء بإلزام المطلوب الأمر ضده بسداد المبلغ محل الطلب مع الرسوم.',1);
تتلخص وقائع هذه الدعوى في أن المدعي قد تضرر من المدعى عليه على النحو المبين.',1);
استناداً إلى القوانين النافذة وأحكام الشريعة الإسلامية.',1);
نلتمس الحكم وفقاً لما ورد أعلاه.',1);
وحيث إن الاستئناف قُدم في الميعاد القانوني المستوجب قبوله شكلاً.',1);
وحيث إن الحكم المستأنف قد جانبه الصواب في التطبيق.',1);
بُني الطعن على مخالفة القانون والخطأ في تطبيقه.',1);
CREATE TABLE "legal_articles" ("id" integer NOT NULL PRIMARY KEY , "source_title" varchar(255) NOT NULL, "book_title" varchar(255) NULL, "section_title" varchar(255) NULL, "chapter_title" varchar(255) NULL, "branch_title" varchar(255) NULL, "article_number" varchar(50) NOT NULL, "article_text" text NOT NULL, "created_at" timestamp NOT NULL);
CREATE TABLE "logs_aichatlog" ("id" integer NOT NULL PRIMARY KEY , "question" text NOT NULL, "answer" text NOT NULL, "created_at" timestamp NOT NULL, "model_version" varchar(100) NULL, "user_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "logs_searchlog" ("id" integer NOT NULL PRIMARY KEY , "search_query" text NOT NULL, "search_date" timestamp NOT NULL, "results_count" integer NULL CHECK ("results_count" >= 0), "user_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "logs_usersession" ("id" integer NOT NULL PRIMARY KEY , "device_type" varchar(100) NULL, "browser" varchar(100) NULL, "ip_address" char(39) NULL, "country" varchar(100) NULL, "governorate" varchar(100) NULL, "city" varchar(100) NULL, "login_time" timestamp NOT NULL, "logout_time" timestamp NULL, "is_active" bool NOT NULL, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "parties_defendant" ("id" integer NOT NULL PRIMARY KEY , "name" varchar(200) NOT NULL, "gender" varchar(10) NOT NULL, "nationality" varchar(100) NOT NULL, "occupation" varchar(200) NULL, "address" text NOT NULL, "phone" varchar(20) NULL, "attorney_name" varchar(200) NULL, "attorney_phone" varchar(20) NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, "lawsuit_id" bigint NOT NULL REFERENCES "lawsuits_lawsuit" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "parties_plaintiff" ("id" integer NOT NULL PRIMARY KEY , "name" varchar(200) NOT NULL, "gender" varchar(10) NOT NULL, "nationality" varchar(100) NOT NULL, "occupation" varchar(200) NULL, "address" text NOT NULL, "phone" varchar(20) NULL, "attorney_name" varchar(200) NULL, "attorney_phone" varchar(20) NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, "lawsuit_id" bigint NOT NULL REFERENCES "lawsuits_lawsuit" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "payments_paymentorder" ("id" integer NOT NULL PRIMARY KEY , "amount" decimal NOT NULL, "order_date" date NOT NULL, "order_number" varchar(100) NULL UNIQUE, "description" text NULL, "status" varchar(50) NOT NULL, "paid_amount" decimal NOT NULL, "payment_date" date NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, "lawsuit_id" bigint NOT NULL REFERENCES "lawsuits_lawsuit" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "responses_response" ("id" integer NOT NULL PRIMARY KEY , "response_text" text NOT NULL, "submitted_by" varchar(200) NOT NULL, "submission_date" date NOT NULL, "hijri_date" varchar(50) NULL, "response_type" varchar(50) NOT NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, "lawsuit_id" bigint NOT NULL REFERENCES "lawsuits_lawsuit" ("id") DEFERRABLE INITIALLY DEFERRED, "submitted_by_user_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_user_groups_user_id_group_id_94350c0c_uniq" ON "auth_user_groups" ("user_id", "group_id");
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id");
CREATE UNIQUE INDEX "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" ON "auth_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id");
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE INDEX "accounts_us_role_e16858_idx" ON "accounts_userprofile" ("role");
CREATE INDEX "accounts_us_nationa_ae502e_idx" ON "accounts_userprofile" ("national_id");
CREATE INDEX "accounts_us_is_acti_993040_idx" ON "accounts_userprofile" ("is_active");
CREATE INDEX "appeals_appeal_lawsuit_id_fc1990c7" ON "appeals_appeal" ("lawsuit_id");
CREATE INDEX "appeals_appeal_submitted_by_user_id_ac20e584" ON "appeals_appeal" ("submitted_by_user_id");
CREATE INDEX "appeals_app_lawsuit_fb59ed_idx" ON "appeals_appeal" ("lawsuit_id");
CREATE INDEX "appeals_app_appeal__9ea8ac_idx" ON "appeals_appeal" ("appeal_number");
CREATE INDEX "appeals_app_appeal__a2d79a_idx" ON "appeals_appeal" ("appeal_type");
CREATE INDEX "appeals_app_status_5d3c4a_idx" ON "appeals_appeal" ("status");
CREATE INDEX "appeals_app_appeal__36c8b5_idx" ON "appeals_appeal" ("appeal_date");
CREATE INDEX "attachments_attachment_lawsuit_id_5c9fe600" ON "attachments_attachment" ("lawsuit_id");
CREATE INDEX "attachments_lawsuit_34dc7e_idx" ON "attachments_attachment" ("lawsuit_id");
CREATE INDEX "attachments_documen_5a76b4_idx" ON "attachments_attachment" ("document_type");
CREATE INDEX "attachments_gregori_f30149_idx" ON "attachments_attachment" ("gregorian_date");
CREATE INDEX "audit_auditlog_timestamp_3c0fe3f7" ON "audit_auditlog" ("timestamp");
CREATE INDEX "audit_auditlog_lawsuit_id_29a6286d" ON "audit_auditlog" ("lawsuit_id");
CREATE INDEX "audit_auditlog_user_id_c1cca96c" ON "audit_auditlog" ("user_id");
CREATE INDEX "audit_audit_action__dd3a3c_idx" ON "audit_auditlog" ("action_type");
CREATE INDEX "audit_audit_user_id_292c79_idx" ON "audit_auditlog" ("user_id");
CREATE INDEX "audit_audit_lawsuit_bb4ada_idx" ON "audit_auditlog" ("lawsuit_id");
CREATE INDEX "audit_audit_timesta_19e18a_idx" ON "audit_auditlog" ("timestamp");
CREATE INDEX "audit_audit_action__8d4ad5_idx" ON "audit_auditlog" ("action_type", "lawsuit_id");
CREATE INDEX "hearings_hearing_created_by_id_dc88096f" ON "hearings_hearing" ("created_by_id");
CREATE INDEX "hearings_hearing_judge_id_a4bdfdd9" ON "hearings_hearing" ("judge_id");
CREATE INDEX "hearings_hearing_lawsuit_id_670a6359" ON "hearings_hearing" ("lawsuit_id");
CREATE INDEX "hearings_he_lawsuit_c01781_idx" ON "hearings_hearing" ("lawsuit_id");
CREATE INDEX "hearings_he_hearing_493fc5_idx" ON "hearings_hearing" ("hearing_date");
CREATE INDEX "hearings_he_hearing_439b65_idx" ON "hearings_hearing" ("hearing_type");
CREATE INDEX "hearings_he_judge_i_e33d2a_idx" ON "hearings_hearing" ("judge_id");
CREATE UNIQUE INDEX "judgments_judgment_lawsuit_id_judgment_number_629bdf44_uniq" ON "judgments_judgment" ("lawsuit_id", "judgment_number");
CREATE INDEX "judgments_judgment_created_by_id_f6ede2a9" ON "judgments_judgment" ("created_by_id");
CREATE INDEX "judgments_judgment_judge_id_b17ccb50" ON "judgments_judgment" ("judge_id");
CREATE INDEX "judgments_judgment_lawsuit_id_81bba762" ON "judgments_judgment" ("lawsuit_id");
CREATE INDEX "judgments_j_lawsuit_720ee7_idx" ON "judgments_judgment" ("lawsuit_id");
CREATE INDEX "judgments_j_judgmen_4d20f6_idx" ON "judgments_judgment" ("judgment_type");
CREATE INDEX "judgments_j_judgmen_4cc752_idx" ON "judgments_judgment" ("judgment_date");
CREATE INDEX "judgments_j_status_8dbe7a_idx" ON "judgments_judgment" ("status");
CREATE INDEX "judgments_j_judge_i_603738_idx" ON "judgments_judgment" ("judge_id");
CREATE INDEX "parties_defendant_lawsuit_id_a3bff871" ON "parties_defendant" ("lawsuit_id");
CREATE INDEX "parties_def_lawsuit_f79796_idx" ON "parties_defendant" ("lawsuit_id");
CREATE INDEX "parties_def_name_ba5f92_idx" ON "parties_defendant" ("name");
CREATE INDEX "parties_plaintiff_lawsuit_id_d895b204" ON "parties_plaintiff" ("lawsuit_id");
CREATE INDEX "parties_pla_lawsuit_f68907_idx" ON "parties_plaintiff" ("lawsuit_id");
CREATE INDEX "parties_pla_name_4ce469_idx" ON "parties_plaintiff" ("name");
CREATE INDEX "responses_response_lawsuit_id_c948fdd7" ON "responses_response" ("lawsuit_id");
CREATE INDEX "responses_response_submitted_by_user_id_3b6eac1d" ON "responses_response" ("submitted_by_user_id");
CREATE INDEX "responses_r_lawsuit_ff1408_idx" ON "responses_response" ("lawsuit_id");
CREATE INDEX "responses_r_submiss_30fae1_idx" ON "responses_response" ("submission_date");
CREATE INDEX "responses_r_respons_ea5752_idx" ON "responses_response" ("response_type");
CREATE INDEX "responses_r_submitt_988950_idx" ON "responses_response" ("submitted_by_user_id");
CREATE INDEX "courts_dist_governo_cfc9ac_idx" ON "courts_district" ("governorate_id");
CREATE INDEX "courts_dist_name_ae873d_idx" ON "courts_district" ("name");
CREATE UNIQUE INDEX "courts_district_governorate_id_name_c46c0675_uniq" ON "courts_district" ("governorate_id", "name");
CREATE INDEX "courts_cour_court_t_672f1b_idx" ON "courts_court" ("court_type_id");
CREATE INDEX "courts_cour_governo_ccf450_idx" ON "courts_court" ("governorate_id");
CREATE INDEX "courts_cour_distric_38db7e_idx" ON "courts_court" ("district_id");
CREATE INDEX "courts_cour_is_acti_bc541b_idx" ON "courts_court" ("is_active");
CREATE INDEX "courts_cour_name_5420b0_idx" ON "courts_courtspecialization" ("name");
CREATE INDEX "courts_cour_judicia_505385_idx" ON "courts_courttype" ("judicial_level");
CREATE INDEX "courts_cour_name_993757_idx" ON "courts_courttype" ("name");
CREATE INDEX "courts_gove_name_233d72_idx" ON "courts_governorate" ("name");
CREATE INDEX "courts_district_governorate_id_2ced8d4e" ON "courts_district" ("governorate_id");
CREATE INDEX "courts_court_court_type_id_0eb4bd4b" ON "courts_court" ("court_type_id");
CREATE INDEX "courts_court_district_id_039a72b7" ON "courts_court" ("district_id");
CREATE INDEX "courts_court_governorate_id_f86900d5" ON "courts_court" ("governorate_id");
CREATE UNIQUE INDEX "courts_court_specializations_court_id_courtspecialization_id_89d87e22_uniq" ON "courts_court_specializations" ("court_id", "courtspecialization_id");
CREATE INDEX "courts_court_specializations_court_id_5d74e06e" ON "courts_court_specializations" ("court_id");
CREATE INDEX "courts_court_specializations_courtspecialization_id_f5735a92" ON "courts_court_specializations" ("courtspecialization_id");
CREATE INDEX "laws_lawcha_law_id_fda1fc_idx" ON "laws_lawchapter" ("law_id");
CREATE INDEX "laws_lawcha_order_679bb7_idx" ON "laws_lawchapter" ("order");
CREATE INDEX "laws_lawsec_chapter_e40262_idx" ON "laws_lawsection" ("chapter_id");
CREATE INDEX "laws_lawsec_order_63f439_idx" ON "laws_lawsection" ("order");
CREATE INDEX "laws_lawart_section_5a16a1_idx" ON "laws_lawarticle" ("section_id");
CREATE INDEX "laws_lawart_article_8f4abb_idx" ON "laws_lawarticle" ("article_number");
CREATE INDEX "laws_lawart_order_4d95ed_idx" ON "laws_lawarticle" ("order");
CREATE UNIQUE INDEX "laws_lawarticle_section_id_article_number_dc0a5a36_uniq" ON "laws_lawarticle" ("section_id", "article_number");
CREATE INDEX "laws_law_categor_69c984_idx" ON "laws_law" ("category_id");
CREATE INDEX "laws_law_issue_y_fbb3b4_idx" ON "laws_law" ("issue_year");
CREATE INDEX "laws_law_name_e754df_idx" ON "laws_law" ("name");
CREATE INDEX "laws_lawchapter_law_id_83707ab0" ON "laws_lawchapter" ("law_id");
CREATE INDEX "laws_lawsection_chapter_id_5ab587d9" ON "laws_lawsection" ("chapter_id");
CREATE INDEX "laws_lawarticle_section_id_4b1350a8" ON "laws_lawarticle" ("section_id");
CREATE INDEX "laws_legalc_name_936ee1_idx" ON "laws_legalcategory" ("name");
CREATE INDEX "laws_law_category_id_ee14ca83" ON "laws_law" ("category_id");
CREATE INDEX "laws_caselegalreference_lawsuit_id_78101e54" ON "laws_caselegalreference" ("lawsuit_id");
CREATE INDEX "laws_caselegalreference_article_id_e96413f7" ON "laws_caselegalreference" ("article_id");
CREATE INDEX "laws_casele_lawsuit_4d3ad5_idx" ON "laws_caselegalreference" ("lawsuit_id");
CREATE INDEX "laws_casele_article_1f201e_idx" ON "laws_caselegalreference" ("article_id");
CREATE INDEX "laws_casele_confide_2dc89e_idx" ON "laws_caselegalreference" ("confidence_score");
CREATE INDEX "laws_casele_is_ai_0b4b1b_idx" ON "laws_caselegalreference" ("is_ai");
CREATE INDEX "logs_aichatlog_user_id_7cffc220" ON "logs_aichatlog" ("user_id");
CREATE INDEX "logs_aichat_user_id_61b51d_idx" ON "logs_aichatlog" ("user_id");
CREATE INDEX "logs_aichat_created_f62781_idx" ON "logs_aichatlog" ("created_at");
CREATE INDEX "logs_searchlog_user_id_5f092777" ON "logs_searchlog" ("user_id");
CREATE INDEX "logs_search_user_id_90cb60_idx" ON "logs_searchlog" ("user_id");
CREATE INDEX "logs_search_search__6b2530_idx" ON "logs_searchlog" ("search_date");
CREATE INDEX "logs_usersession_user_id_239ce00c" ON "logs_usersession" ("user_id");
CREATE INDEX "logs_userse_user_id_bc4a92_idx" ON "logs_usersession" ("user_id");
CREATE INDEX "logs_userse_login_t_569963_idx" ON "logs_usersession" ("login_time");
CREATE INDEX "logs_userse_is_acti_ab3554_idx" ON "logs_usersession" ("is_active");
CREATE INDEX "payments_paymentorder_lawsuit_id_e47675da" ON "payments_paymentorder" ("lawsuit_id");
CREATE INDEX "payments_pa_lawsuit_e7e6c7_idx" ON "payments_paymentorder" ("lawsuit_id");
CREATE INDEX "payments_pa_order_d_de1a5f_idx" ON "payments_paymentorder" ("order_date");
CREATE INDEX "payments_pa_status_75a59b_idx" ON "payments_paymentorder" ("status");
CREATE INDEX "payments_pa_order_n_0698ad_idx" ON "payments_paymentorder" ("order_number");
CREATE INDEX "lawsuits_lawsuit_created_by_id_8225a10d" ON "lawsuits_lawsuit" ("created_by_id");
CREATE INDEX "lawsuits_lawsuit_court_fk_id_3d845ffa" ON "lawsuits_lawsuit" ("court_fk_id");
CREATE INDEX "lawsuits_la_case_nu_1e6e0c_idx" ON "lawsuits_lawsuit" ("case_number");
CREATE INDEX "lawsuits_la_status_213658_idx" ON "lawsuits_lawsuit" ("status");
CREATE INDEX "lawsuits_la_case_ty_4a333a_idx" ON "lawsuits_lawsuit" ("case_type");
CREATE INDEX "lawsuits_la_created_a378e0_idx" ON "lawsuits_lawsuit" ("created_at");
CREATE INDEX "lawsuits_la_filing__b33206_idx" ON "lawsuits_lawsuit" ("filing_date");
CREATE INDEX "lawsuits_la_court_f_d933df_idx" ON "lawsuits_lawsuit" ("court_fk_id");
CREATE INDEX "lawsuits_la_created_dad0ff_idx" ON "lawsuits_lawsuit" ("created_by_id");
CREATE INDEX "lawsuits_la_case_st_9b76b6_idx" ON "lawsuits_lawsuit" ("case_status");
CREATE INDEX "lawsuits_financialclaim_lawsuit_id_a1ec8bbc" ON "lawsuits_financialclaim" ("lawsuit_id");
CREATE INDEX "lawsuits_le_case_ty_794e41_idx" ON "lawsuits_legaltemplate" ("case_type");
CREATE INDEX "lawsuits_le_section_30b5e1_idx" ON "lawsuits_legaltemplate" ("section_key");
CREATE UNIQUE INDEX "lawsuits_legaltemplate_case_type_section_key_f0fa0f6a_uniq" ON "lawsuits_legaltemplate" ("case_type", "section_key");
CREATE INDEX "lawsuits_fi_lawsuit_6d3fd9_idx" ON "lawsuits_financialclaim" ("lawsuit_id");
CREATE INDEX "lawsuits_fi_amount_db009a_idx" ON "lawsuits_financialclaim" ("amount");
CREATE INDEX "book_nodes_title_3f0458_idx" ON "book_nodes" ("title");
DELETE FROM "sqlite_sequence";