# Generated by Django 5.2.9 on 2026-01-06 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='السؤال')),
                ('answer', models.TextField(verbose_name='الإجابة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('model_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='إصدار النموذج')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_chat_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل محادثة AI',
                'verbose_name_plural': 'سجلات محادثات AI',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='logs_aichat_user_id_61b51d_idx'), models.Index(fields=['created_at'], name='logs_aichat_created_f62781_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.TextField(verbose_name='استعلام البحث')),
                ('search_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البحث')),
                ('results_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد النتائج')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل بحث',
                'verbose_name_plural': 'سجلات البحث',
                'ordering': ['-search_date'],
                'indexes': [models.Index(fields=['user'], name='logs_search_user_id_90cb60_idx'), models.Index(fields=['search_date'], name='logs_search_search__6b2530_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع الجهاز')),
                ('browser', models.CharField(blank=True, max_length=100, null=True, verbose_name='المتصفح')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='الدولة')),
                ('governorate', models.CharField(blank=True, max_length=100, null=True, verbose_name='المحافظة')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='وقت تسجيل الدخول')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت تسجيل الخروج')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'جلسة مستخدم',
                'verbose_name_plural': 'جلسات المستخدمين',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['user'], name='logs_userse_user_id_bc4a92_idx'), models.Index(fields=['login_time'], name='logs_userse_login_t_569963_idx'), models.Index(fields=['is_active'], name='logs_userse_is_acti_ab3554_idx')],
            },
        ),
    ]
