# Generated by Django 5.2.9 on 2026-01-04 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lawsuits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal_type', models.CharField(choices=[('primary', 'ابتدائي'), ('appeal', 'استئناف'), ('cassation', 'تمييز'), ('constitutional', 'دستوري'), ('other', 'أخرى')], default='appeal', max_length=50, verbose_name='نوع الطعن')),
                ('appeal_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='رقم الطعن')),
                ('appeal_reasons', models.TextField(verbose_name='أسباب الطعن')),
                ('appeal_requests', models.TextField(verbose_name='طلبات الطعن')),
                ('higher_court', models.CharField(max_length=200, verbose_name='المحكمة الأعلى')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('under_review', 'قيد المراجعة'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('withdrawn', 'مسحوب'), ('closed', 'مغلق')], default='pending', max_length=50, verbose_name='حالة الطعن')),
                ('appeal_date', models.DateField(verbose_name='تاريخ الطعن')),
                ('hijri_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='التاريخ الهجري')),
                ('submitted_by', models.CharField(max_length=200, verbose_name='مقدم الطعن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('lawsuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='lawsuits.lawsuit', verbose_name='الدعوى')),
                ('submitted_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_appeals', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المقدم')),
            ],
            options={
                'verbose_name': 'طعن',
                'verbose_name_plural': 'طعون',
                'ordering': ['-appeal_date', '-created_at'],
                'indexes': [models.Index(fields=['lawsuit'], name='appeals_app_lawsuit_fb59ed_idx'), models.Index(fields=['appeal_number'], name='appeals_app_appeal__9ea8ac_idx'), models.Index(fields=['appeal_type'], name='appeals_app_appeal__a2d79a_idx'), models.Index(fields=['status'], name='appeals_app_status_5d3c4a_idx'), models.Index(fields=['appeal_date'], name='appeals_app_appeal__36c8b5_idx')],
            },
        ),
    ]
