# Generated by Django 5.2.9 on 2026-01-04 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lawsuits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Judgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judgment_type', models.CharField(choices=[('primary', 'ابتدائي'), ('appeal', 'استئناف'), ('final', 'بات')], default='primary', max_length=50, verbose_name='نوع الحكم')),
                ('judgment_number', models.CharField(max_length=100, verbose_name='رقم الحكم')),
                ('judgment_date', models.DateField(verbose_name='تاريخ الحكم')),
                ('hijri_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='التاريخ الهجري')),
                ('judgment_text', models.TextField(verbose_name='نص الحكم')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='ملخص الحكم')),
                ('judge_name', models.CharField(max_length=200, verbose_name='اسم القاضي')),
                ('court_name', models.CharField(max_length=200, verbose_name='اسم المحكمة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('executable', 'قابل للتنفيذ'), ('appealed', 'تم الطعن'), ('final', 'بات'), ('executed', 'تم التنفيذ')], default='pending', max_length=50, verbose_name='حالة الحكم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_judgments', to=settings.AUTH_USER_MODEL, verbose_name='منشئ السجل')),
                ('judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_judgments', to=settings.AUTH_USER_MODEL, verbose_name='القاضي')),
                ('lawsuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judgments', to='lawsuits.lawsuit', verbose_name='الدعوى')),
            ],
            options={
                'verbose_name': 'حكم',
                'verbose_name_plural': 'أحكام',
                'ordering': ['-judgment_date', '-created_at'],
                'indexes': [models.Index(fields=['lawsuit'], name='judgments_j_lawsuit_720ee7_idx'), models.Index(fields=['judgment_type'], name='judgments_j_judgmen_4d20f6_idx'), models.Index(fields=['judgment_date'], name='judgments_j_judgmen_4cc752_idx'), models.Index(fields=['status'], name='judgments_j_status_8dbe7a_idx'), models.Index(fields=['judge'], name='judgments_j_judge_i_603738_idx')],
                'unique_together': {('lawsuit', 'judgment_number')},
            },
        ),
    ]
