# Generated by Django 6.0.1 on 2026-03-18 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgments', '0001_initial'),
        ('lawsuits', '0004_add_archive_lifecycle_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='judgment',
            name='court_level',
            field=models.CharField(choices=[('first_instance', 'ابتدائي'), ('appeal', 'استئناف'), ('supreme', 'عليا / تمييز')], default='first_instance', max_length=30, verbose_name='درجة المحكمة'),
        ),
        migrations.AddField(
            model_name='judgment',
            name='document_reference',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='مرجع الوثيقة'),
        ),
        migrations.AlterField(
            model_name='judgment',
            name='judgment_type',
            field=models.CharField(choices=[('primary', 'ابتدائي'), ('appeal', 'استئناف'), ('final', 'بات'), ('conviction', 'إدانة'), ('acquittal', 'تبرئة'), ('civil_for', 'قضي للمدعي'), ('civil_against', 'قضي على المدعى عليه'), ('dismissed', 'رُفضت الدعوى'), ('partial', 'حكم جزئي'), ('other', 'أخرى')], default='primary', max_length=50, verbose_name='نوع الحكم'),
        ),
        migrations.AddIndex(
            model_name='judgment',
            index=models.Index(fields=['court_level'], name='judgments_j_court_l_7cf141_idx'),
        ),
    ]
