# Generated by Django 5.2.9 on 2026-01-04 22:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawsuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='رقم الدعوى')),
                ('gregorian_date', models.DateField(verbose_name='التاريخ الميلادي')),
                ('hijri_date', models.CharField(max_length=50, verbose_name='التاريخ الهجري')),
                ('case_type', models.CharField(choices=[('civil', 'مدني'), ('commercial', 'تجاري'), ('criminal', 'جنائي'), ('personal_status', 'أحوال شخصية'), ('labor', 'عمل'), ('administrative', 'إداري'), ('other', 'أخرى')], default='civil', max_length=50, verbose_name='نوع الدعوى')),
                ('court', models.CharField(max_length=200, verbose_name='المحكمة')),
                ('subject', models.CharField(max_length=150, validators=[django.core.validators.MaxLengthValidator(150)], verbose_name='موضوع الدعوى')),
                ('facts', models.TextField(verbose_name='وقائع الدعوى')),
                ('reasons', models.TextField(verbose_name='الأسباب والأسانيد')),
                ('requests', models.TextField(verbose_name='الطلبات')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد النظر'), ('under_review', 'قيد المراجعة'), ('judged', 'تم الحكم'), ('appealed', 'تم الطعن'), ('closed', 'مغلقة')], default='pending', max_length=50, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lawsuits', to=settings.AUTH_USER_MODEL, verbose_name='منشئ الدعوى')),
            ],
            options={
                'verbose_name': 'دعوى',
                'verbose_name_plural': 'دعاوى',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case_number'], name='lawsuits_la_case_nu_1e6e0c_idx'), models.Index(fields=['status'], name='lawsuits_la_status_213658_idx'), models.Index(fields=['case_type'], name='lawsuits_la_case_ty_4a333a_idx'), models.Index(fields=['created_at'], name='lawsuits_la_created_a378e0_idx'), models.Index(fields=['gregorian_date'], name='lawsuits_la_gregori_636e1b_idx')],
            },
        ),
    ]
