# Generated by Django 5.2.9 on 2026-01-06 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '__first__'),
        ('lawsuits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lawsuit',
            name='lawsuits_la_gregori_636e1b_idx',
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='court_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lawsuits', to='courts.court', verbose_name='المحكمة'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='filing_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ رفع الدعوى'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='legal_basis',
            field=models.TextField(blank=True, null=True, verbose_name='الأساس القانوني'),
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='court',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='المحكمة (نص)'),
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='facts',
            field=models.TextField(blank=True, null=True, verbose_name='وقائع الدعوى'),
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='gregorian_date',
            field=models.DateField(blank=True, null=True, verbose_name='التاريخ الميلادي'),
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='hijri_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='التاريخ الهجري'),
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='reasons',
            field=models.TextField(blank=True, null=True, verbose_name='الأسباب والأسانيد'),
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='requests',
            field=models.TextField(blank=True, null=True, verbose_name='الطلبات'),
        ),
        migrations.AddIndex(
            model_name='lawsuit',
            index=models.Index(fields=['filing_date'], name='lawsuits_la_filing__b33206_idx'),
        ),
        migrations.AddIndex(
            model_name='lawsuit',
            index=models.Index(fields=['court_fk'], name='lawsuits_la_court_f_d933df_idx'),
        ),
        migrations.AddIndex(
            model_name='lawsuit',
            index=models.Index(fields=['created_by'], name='lawsuits_la_created_dad0ff_idx'),
        ),
    ]
