# Generated by Django 5.2.9 on 2026-01-06 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
        ('lawsuits', '0002_remove_lawsuit_lawsuits_la_gregori_636e1b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='المبلغ')),
                ('currency', models.CharField(choices=[('YER', 'ريال يمني'), ('USD', 'دولار أمريكي'), ('SAR', 'ريال سعودي'), ('EGP', 'جنيه مصري')], default='YER', max_length=3, verbose_name='العملة')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'مطالبة مالية',
                'verbose_name_plural': 'مطالبات مالية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('امر_اداء', 'أمر أداء'), ('دعوى', 'دعوى'), ('رد_على_دعوى', 'رد على دعوى'), ('استئناف', 'استئناف'), ('طعن', 'طعن')], max_length=50, verbose_name='نوع القضية')),
                ('section_key', models.CharField(max_length=50, verbose_name='مفتاح القسم')),
                ('section_title', models.CharField(max_length=100, verbose_name='عنوان القسم')),
                ('default_text', models.TextField(verbose_name='النص الافتراضي')),
                ('is_required', models.BooleanField(default=True, verbose_name='إجباري')),
            ],
            options={
                'verbose_name': 'نص قانوني',
                'verbose_name_plural': 'نصوص قانونية',
            },
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='case_status',
            field=models.CharField(choices=[('جديد', 'جديد'), ('قيد_النظر', 'قيد النظر'), ('مكتمل', 'مكتمل'), ('مغلق', 'مغلق')], default='جديد', max_length=50, verbose_name='حالة القضية'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='governorate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='legal_reasons',
            field=models.TextField(blank=True, null=True, verbose_name='الأسباب القانونية'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='case_type',
            field=models.CharField(choices=[('امر_اداء', 'أمر أداء'), ('دعوى', 'دعوى'), ('رد_على_دعوى', 'رد على دعوى'), ('استئناف', 'استئناف'), ('طعن', 'طعن'), ('civil', 'مدني'), ('commercial', 'تجاري'), ('criminal', 'جنائي'), ('personal_status', 'أحوال شخصية'), ('labor', 'عمل'), ('administrative', 'إداري'), ('other', 'أخرى')], default='دعوى', max_length=50, verbose_name='نوع الدعوى'),
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد النظر'), ('under_review', 'قيد المراجعة'), ('judged', 'تم الحكم'), ('appealed', 'تم الطعن'), ('closed', 'مغلقة')], default='pending', max_length=50, verbose_name='الحالة (قديم)'),
        ),
        migrations.AddIndex(
            model_name='lawsuit',
            index=models.Index(fields=['case_status'], name='lawsuits_la_case_st_9b76b6_idx'),
        ),
        migrations.AddField(
            model_name='financialclaim',
            name='lawsuit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_claims', to='lawsuits.lawsuit', verbose_name='الدعوى'),
        ),
        migrations.AddIndex(
            model_name='legaltemplate',
            index=models.Index(fields=['case_type'], name='lawsuits_le_case_ty_794e41_idx'),
        ),
        migrations.AddIndex(
            model_name='legaltemplate',
            index=models.Index(fields=['section_key'], name='lawsuits_le_section_30b5e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='legaltemplate',
            unique_together={('case_type', 'section_key')},
        ),
        migrations.AddIndex(
            model_name='financialclaim',
            index=models.Index(fields=['lawsuit'], name='lawsuits_fi_lawsuit_6d3fd9_idx'),
        ),
        migrations.AddIndex(
            model_name='financialclaim',
            index=models.Index(fields=['amount'], name='lawsuits_fi_amount_db009a_idx'),
        ),
    ]
