# Generated by Django 6.0.1 on 2026-03-18 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
        ('lawsuits', '0004_add_archive_lifecycle_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lawsuit',
            name='ai_summary',
            field=models.TextField(blank=True, null=True, verbose_name='الملخص الذكي'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='court_level',
            field=models.CharField(blank=True, choices=[('first_instance', 'ابتدائي'), ('appeal', 'استئناف'), ('supreme', 'عليا / تمييز')], max_length=30, null=True, verbose_name='درجة المحكمة'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='الشعبة / الدائرة'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='lawyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lawyer_lawsuits', to=settings.AUTH_USER_MODEL, verbose_name='المحامي'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='legal_risk_level',
            field=models.CharField(blank=True, choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالٍ')], max_length=10, null=True, verbose_name='مستوى المخاطرة'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='rag_metadata',
            field=models.TextField(blank=True, null=True, verbose_name='بيانات RAG الوصفية'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='related_laws',
            field=models.JSONField(blank=True, default=list, verbose_name='المواد القانونية المرتبطة'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='similar_cases',
            field=models.JSONField(blank=True, default=list, verbose_name='القضايا المشابهة'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='success_probability',
            field=models.FloatField(blank=True, null=True, verbose_name='احتمالية النجاح'),
        ),
        migrations.AddIndex(
            model_name='lawsuit',
            index=models.Index(fields=['court_level'], name='lawsuits_la_court_l_26252f_idx'),
        ),
        migrations.AddIndex(
            model_name='lawsuit',
            index=models.Index(fields=['lawyer'], name='lawsuits_la_lawyer__cd6cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='lawsuit',
            index=models.Index(fields=['legal_risk_level'], name='lawsuits_la_legal_r_30718a_idx'),
        ),
    ]
