# Generated by Django 6.0.1 on 2026-03-28 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
        ('lawsuits', '0005_archive_system_improvements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lawsuit',
            name='citizen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_lawsuits', to=settings.AUTH_USER_MODEL, verbose_name='المواطن'),
        ),
        migrations.AddIndex(
            model_name='lawsuit',
            index=models.Index(fields=['citizen'], name='lawsuits_la_citizen_d7fbc2_idx'),
        ),
    ]
