# Generated by Django 5.2.9 on 2026-01-06 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lawsuits', '0002_remove_lawsuit_lawsuits_la_gregori_636e1b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='المبلغ')),
                ('order_date', models.DateField(verbose_name='تاريخ الأمر')),
                ('order_number', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='رقم الأمر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('paid', 'مدفوع'), ('partial', 'مدفوع جزئياً'), ('cancelled', 'ملغي')], default='pending', max_length=50, verbose_name='حالة الدفع')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='المبلغ المدفوع')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('lawsuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='lawsuits.lawsuit', verbose_name='الدعوى')),
            ],
            options={
                'verbose_name': 'أمر دفع',
                'verbose_name_plural': 'أوامر الدفع',
                'ordering': ['-order_date', '-created_at'],
                'indexes': [models.Index(fields=['lawsuit'], name='payments_pa_lawsuit_e7e6c7_idx'), models.Index(fields=['order_date'], name='payments_pa_order_d_de1a5f_idx'), models.Index(fields=['status'], name='payments_pa_status_75a59b_idx'), models.Index(fields=['order_number'], name='payments_pa_order_n_0698ad_idx')],
            },
        ),
    ]
