# Generated by Django 5.2.9 on 2026-01-04 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lawsuits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('lawsuit_created', 'إنشاء دعوى'), ('party_added', 'إضافة طرف'), ('attachment_uploaded', 'رفع مرفق'), ('response_submitted', 'تقديم رد'), ('appeal_filed', 'تقديم طعن'), ('judgment_issued', 'إصدار حكم'), ('hearing_scheduled', 'جدولة جلسة'), ('other', 'أخرى')], max_length=50, verbose_name='نوع الإجراء')),
                ('description', models.TextField(verbose_name='وصف الإجراء')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='الوقت')),
                ('lawsuit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='lawsuits.lawsuit', verbose_name='الدعوى')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل إجراء',
                'verbose_name_plural': 'سجل الإجراءات',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action_type'], name='audit_audit_action__dd3a3c_idx'), models.Index(fields=['user'], name='audit_audit_user_id_292c79_idx'), models.Index(fields=['lawsuit'], name='audit_audit_lawsuit_bb4ada_idx'), models.Index(fields=['timestamp'], name='audit_audit_timesta_19e18a_idx'), models.Index(fields=['action_type', 'lawsuit'], name='audit_audit_action__8d4ad5_idx')],
            },
        ),
    ]
