# Generated by Django 5.2.9 on 2026-01-04 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lawsuits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='الجنس')),
                ('nationality', models.CharField(max_length=100, verbose_name='الجنسية')),
                ('occupation', models.CharField(blank=True, max_length=200, null=True, verbose_name='المهنة')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='الهاتف')),
                ('attorney_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم الوكيل')),
                ('attorney_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='هاتف الوكيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('lawsuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defendants', to='lawsuits.lawsuit', verbose_name='الدعوى')),
            ],
            options={
                'verbose_name': 'مدعى عليه',
                'verbose_name_plural': 'مدعى عليهم',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lawsuit'], name='parties_def_lawsuit_f79796_idx'), models.Index(fields=['name'], name='parties_def_name_ba5f92_idx')],
            },
        ),
        migrations.CreateModel(
            name='Plaintiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='الجنس')),
                ('nationality', models.CharField(max_length=100, verbose_name='الجنسية')),
                ('occupation', models.CharField(blank=True, max_length=200, null=True, verbose_name='المهنة')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='الهاتف')),
                ('attorney_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم الوكيل')),
                ('attorney_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='هاتف الوكيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('lawsuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plaintiffs', to='lawsuits.lawsuit', verbose_name='الدعوى')),
            ],
            options={
                'verbose_name': 'مدعي',
                'verbose_name_plural': 'مدعون',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lawsuit'], name='parties_pla_lawsuit_f68907_idx'), models.Index(fields=['name'], name='parties_pla_name_4ce469_idx')],
            },
        ),
    ]
