# Generated by Django 6.0.1 on 2026-03-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defendant',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهوية'),
        ),
        migrations.AddField(
            model_name='defendant',
            name='role',
            field=models.CharField(default='defendant', max_length=20, verbose_name='الدور'),
        ),
        migrations.AddField(
            model_name='plaintiff',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهوية'),
        ),
        migrations.AddField(
            model_name='plaintiff',
            name='role',
            field=models.CharField(default='plaintiff', max_length=20, verbose_name='الدور'),
        ),
    ]
