# Generated by Django 5.2.9 on 2026-01-04 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lawsuits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_date', models.DateField(verbose_name='تاريخ الجلسة')),
                ('hijri_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='التاريخ الهجري')),
                ('hearing_time', models.TimeField(blank=True, null=True, verbose_name='وقت الجلسة')),
                ('notes', models.TextField(verbose_name='ملاحظات الجلسة')),
                ('judge_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم القاضي')),
                ('hearing_type', models.CharField(choices=[('preliminary', 'تمهيدية'), ('main', 'رئيسية'), ('decision', 'قرار'), ('adjourned', 'مؤجلة'), ('other', 'أخرى')], default='main', max_length=50, verbose_name='نوع الجلسة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hearings', to=settings.AUTH_USER_MODEL, verbose_name='منشئ السجل')),
                ('judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presided_hearings', to=settings.AUTH_USER_MODEL, verbose_name='القاضي')),
                ('lawsuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='lawsuits.lawsuit', verbose_name='الدعوى')),
            ],
            options={
                'verbose_name': 'جلسة',
                'verbose_name_plural': 'جلسات',
                'ordering': ['-hearing_date', '-hearing_time'],
                'indexes': [models.Index(fields=['lawsuit'], name='hearings_he_lawsuit_c01781_idx'), models.Index(fields=['hearing_date'], name='hearings_he_hearing_493fc5_idx'), models.Index(fields=['hearing_type'], name='hearings_he_hearing_439b65_idx'), models.Index(fields=['judge'], name='hearings_he_judge_i_e33d2a_idx')],
            },
        ),
    ]
