# Generated by Django 6.0.1 on 2026-03-18 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearings', '0001_initial'),
        ('lawsuits', '0004_add_archive_lifecycle_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hearing',
            name='decision',
            field=models.CharField(choices=[('adjourned', 'مؤجلة'), ('judgment', 'صدر حكم'), ('postponed', 'مرجأة'), ('continued', 'تواصل'), ('other', 'أخرى')], default='adjourned', max_length=20, verbose_name='قرار الجلسة'),
        ),
        migrations.AddField(
            model_name='hearing',
            name='next_hearing_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الجلسة القادمة'),
        ),
        migrations.AddField(
            model_name='hearing',
            name='next_hijri_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تاريخ الجلسة القادمة (هجري)'),
        ),
        migrations.AlterField(
            model_name='hearing',
            name='hearing_type',
            field=models.CharField(choices=[('pleading', 'مرافعة'), ('witness', 'سماع شهود'), ('expert', 'تقرير خبير'), ('initial', 'جلسة أولى'), ('judgment', 'جلسة حكم'), ('preliminary', 'تمهيدية'), ('main', 'رئيسية'), ('decision', 'قرار'), ('adjourned', 'مؤجلة'), ('other', 'أخرى')], default='pleading', max_length=50, verbose_name='نوع الجلسة'),
        ),
        migrations.AddIndex(
            model_name='hearing',
            index=models.Index(fields=['decision'], name='hearings_he_decisio_988065_idx'),
        ),
        migrations.AddIndex(
            model_name='hearing',
            index=models.Index(fields=['next_hearing_date'], name='hearings_he_next_he_13d4ab_idx'),
        ),
    ]
