# Generated by Django 5.2.9 on 2026-01-04 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('judge', 'قاضي'), ('lawyer', 'محامي'), ('notary', 'كاتب عدل'), ('citizen', 'مواطن'), ('admin', 'مدير')], default='citizen', max_length=20, verbose_name='الدور')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='الرقم الوطني')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف المستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['role'], name='accounts_us_role_e16858_idx'), models.Index(fields=['national_id'], name='accounts_us_nationa_ae502e_idx'), models.Index(fields=['is_active'], name='accounts_us_is_acti_993040_idx')],
            },
        ),
    ]
