# Generated by Django 5.2.9 on 2026-01-06 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourtSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم التخصص')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تخصص محكمة',
                'verbose_name_plural': 'تخصصات المحاكم',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='courts_cour_name_5420b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='CourtType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نوع المحكمة')),
                ('judicial_level', models.CharField(choices=[('primary', 'ابتدائي'), ('appeal', 'استئناف'), ('cassation', 'تمييز'), ('constitutional', 'دستوري'), ('other', 'أخرى')], default='primary', max_length=50, verbose_name='المستوى القضائي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'نوع محكمة',
                'verbose_name_plural': 'أنواع المحاكم',
                'ordering': ['judicial_level', 'name'],
                'indexes': [models.Index(fields=['judicial_level'], name='courts_cour_judicia_505385_idx'), models.Index(fields=['name'], name='courts_cour_name_993757_idx')],
            },
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم المحافظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'محافظة',
                'verbose_name_plural': 'محافظات',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='courts_gove_name_233d72_idx')],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الحي/المنطقة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='courts.governorate', verbose_name='المحافظة')),
            ],
            options={
                'verbose_name': 'حي/منطقة',
                'verbose_name_plural': 'أحياء/مناطق',
                'ordering': ['governorate', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المحكمة')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('location_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط الموقع')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط الطول')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('specializations', models.ManyToManyField(blank=True, related_name='courts', to='courts.courtspecialization', verbose_name='التخصصات')),
                ('court_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courts', to='courts.courttype', verbose_name='نوع المحكمة')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courts', to='courts.district', verbose_name='الحي/المنطقة')),
                ('governorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courts', to='courts.governorate', verbose_name='المحافظة')),
            ],
            options={
                'verbose_name': 'محكمة',
                'verbose_name_plural': 'محاكم',
                'ordering': ['governorate', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['governorate'], name='courts_dist_governo_cfc9ac_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['name'], name='courts_dist_name_ae873d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('governorate', 'name')},
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['court_type'], name='courts_cour_court_t_672f1b_idx'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['governorate'], name='courts_cour_governo_ccf450_idx'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['district'], name='courts_cour_distric_38db7e_idx'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['is_active'], name='courts_cour_is_acti_bc541b_idx'),
        ),
    ]
