# Generated by Django 5.2.9 on 2026-01-06 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lawsuits', '0002_remove_lawsuit_lawsuits_la_gregori_636e1b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='اسم القانون')),
                ('issue_year', models.IntegerField(blank=True, null=True, verbose_name='سنة الإصدار')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'قانون',
                'verbose_name_plural': 'قوانين',
                'ordering': ['category', 'issue_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LawChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان الفصل')),
                ('chapter_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الفصل')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='laws.law', verbose_name='القانون')),
            ],
            options={
                'verbose_name': 'فصل قانون',
                'verbose_name_plural': 'فصول القوانين',
                'ordering': ['law', 'order', 'chapter_number'],
            },
        ),
        migrations.CreateModel(
            name='LawSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان القسم')),
                ('section_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم القسم')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='laws.lawchapter', verbose_name='الفصل')),
            ],
            options={
                'verbose_name': 'قسم قانون',
                'verbose_name_plural': 'أقسام القوانين',
                'ordering': ['chapter', 'order', 'section_number'],
            },
        ),
        migrations.CreateModel(
            name='LawArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(max_length=50, verbose_name='رقم المادة')),
                ('article_text', models.TextField(verbose_name='نص المادة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='laws.lawsection', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'مادة قانون',
                'verbose_name_plural': 'مواد القوانين',
                'ordering': ['section', 'order', 'article_number'],
            },
        ),
        migrations.CreateModel(
            name='LegalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم الفئة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'فئة قانونية',
                'verbose_name_plural': 'فئات قانونية',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='laws_legalc_name_936ee1_idx')],
            },
        ),
        migrations.AddField(
            model_name='law',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laws', to='laws.legalcategory', verbose_name='الفئة'),
        ),
        migrations.CreateModel(
            name='CaseLegalReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نقاط الثقة')),
                ('is_ai', models.BooleanField(default=False, verbose_name='من AI')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('lawsuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_references', to='lawsuits.lawsuit', verbose_name='الدعوى')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_references', to='laws.lawarticle', verbose_name='المادة القانونية')),
            ],
            options={
                'verbose_name': 'مرجع قانوني',
                'verbose_name_plural': 'مراجع قانونية',
                'ordering': ['-confidence_score', '-created_at'],
                'indexes': [models.Index(fields=['lawsuit'], name='laws_casele_lawsuit_4d3ad5_idx'), models.Index(fields=['article'], name='laws_casele_article_1f201e_idx'), models.Index(fields=['confidence_score'], name='laws_casele_confide_2dc89e_idx'), models.Index(fields=['is_ai'], name='laws_casele_is_ai_0b4b1b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='lawchapter',
            index=models.Index(fields=['law'], name='laws_lawcha_law_id_fda1fc_idx'),
        ),
        migrations.AddIndex(
            model_name='lawchapter',
            index=models.Index(fields=['order'], name='laws_lawcha_order_679bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='lawsection',
            index=models.Index(fields=['chapter'], name='laws_lawsec_chapter_e40262_idx'),
        ),
        migrations.AddIndex(
            model_name='lawsection',
            index=models.Index(fields=['order'], name='laws_lawsec_order_63f439_idx'),
        ),
        migrations.AddIndex(
            model_name='lawarticle',
            index=models.Index(fields=['section'], name='laws_lawart_section_5a16a1_idx'),
        ),
        migrations.AddIndex(
            model_name='lawarticle',
            index=models.Index(fields=['article_number'], name='laws_lawart_article_8f4abb_idx'),
        ),
        migrations.AddIndex(
            model_name='lawarticle',
            index=models.Index(fields=['order'], name='laws_lawart_order_4d95ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lawarticle',
            unique_together={('section', 'article_number')},
        ),
        migrations.AddIndex(
            model_name='law',
            index=models.Index(fields=['category'], name='laws_law_categor_69c984_idx'),
        ),
        migrations.AddIndex(
            model_name='law',
            index=models.Index(fields=['issue_year'], name='laws_law_issue_y_fbb3b4_idx'),
        ),
        migrations.AddIndex(
            model_name='law',
            index=models.Index(fields=['name'], name='laws_law_name_e754df_idx'),
        ),
    ]
