# Generated by Django 5.2.9 on 2026-01-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalArticleFlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_title', models.CharField(max_length=255, verbose_name='المصدر')),
                ('book_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='الكتاب')),
                ('section_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='القسم')),
                ('chapter_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='الفصل')),
                ('branch_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='الفرع')),
                ('article_number', models.CharField(max_length=50, verbose_name='رقم المادة')),
                ('article_text', models.TextField(verbose_name='نص المادة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'مادة قانونية (مسطحة)',
                'verbose_name_plural': 'مواد قانونية (مسطحة)',
                'db_table': 'legal_articles',
            },
        ),
    ]
