# Generated by Django 5.2.9 on 2026-01-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0002_legalarticleflat'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalProcedureNode',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='المعرف')),
                ('source_title', models.CharField(max_length=255, verbose_name='عنوان المصدر')),
                ('level', models.CharField(max_length=50, verbose_name='المستوى')),
                ('title', models.TextField(verbose_name='العنوان')),
                ('body', models.TextField(blank=True, null=True, verbose_name='المحتوى')),
                ('parent_id', models.BigIntegerField(blank=True, null=True, verbose_name='رقم الأب')),
                ('page_from', models.IntegerField(blank=True, null=True, verbose_name='من صفحة')),
                ('page_to', models.IntegerField(blank=True, null=True, verbose_name='إلى صفحة')),
            ],
            options={
                'verbose_name': 'بند دليل الإجراءات',
                'verbose_name_plural': 'بنود دليل الإجراءات',
                'db_table': 'book_nodes',
                'indexes': [models.Index(fields=['title'], name='book_nodes_title_3f0458_idx')],
            },
        ),
    ]
