# Generated by Django 5.2.9 on 2026-01-04 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lawsuits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(verbose_name='نص الرد')),
                ('submitted_by', models.CharField(max_length=200, verbose_name='مقدم الرد')),
                ('submission_date', models.DateField(verbose_name='تاريخ التقديم')),
                ('hijri_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='التاريخ الهجري')),
                ('response_type', models.CharField(choices=[('memorandum', 'مذكرة'), ('reply', 'رد'), ('objection', 'اعتراض'), ('clarification', 'توضيح'), ('other', 'أخرى')], default='reply', max_length=50, verbose_name='نوع الرد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('lawsuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='lawsuits.lawsuit', verbose_name='الدعوى')),
                ('submitted_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_responses', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المقدم')),
            ],
            options={
                'verbose_name': 'رد',
                'verbose_name_plural': 'ردود',
                'ordering': ['-submission_date', '-created_at'],
                'indexes': [models.Index(fields=['lawsuit'], name='responses_r_lawsuit_ff1408_idx'), models.Index(fields=['submission_date'], name='responses_r_submiss_30fae1_idx'), models.Index(fields=['response_type'], name='responses_r_respons_ea5752_idx'), models.Index(fields=['submitted_by_user'], name='responses_r_submitt_988950_idx')],
            },
        ),
    ]
